openapi: 3.0.3
info:
  title: Primis Nexus API (v1)
  version: 1.0.0
servers:
  - url: /api/v1
paths:
  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: OK
